# Generated by Django 3.1.1 on 2020-09-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.category'),
        ),
    ]
