# Generated by Django 3.1.1 on 2020-09-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20200930_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pizza',
            field=models.ManyToManyField(to='pizza.Pizza', verbose_name='Ingredients_list'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.category', verbose_name='pizza'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pizza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza', verbose_name='price'),
        ),
    ]
