# Generated by Django 3.1.1 on 2020-09-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20200930_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.category', verbose_name='pizza_hut'),
        ),
    ]
