# Generated by Django 3.1.1 on 2020-09-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20200930_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pizza',
            field=models.ManyToManyField(to='pizza.Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.category'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pizza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
    ]
