# Generated by Django 3.1.1 on 2020-09-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20200930_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='large_pizza_weight',
        ),
        migrations.RemoveField(
            model_name='price',
            name='medium_pizza_weight',
        ),
        migrations.RemoveField(
            model_name='price',
            name='small_pizza_weight',
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_pizza_weight', models.IntegerField(default=0, max_length=10)),
                ('medium_pizza_weight', models.IntegerField(default=0, max_length=10)),
                ('large_pizza_weight', models.IntegerField(default=0, max_length=10)),
                ('pizza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
        ),
    ]
