# Generated by Django 3.1.1 on 2020-10-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20200930_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(to='pizza.Ingredients'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='large_pizza_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='medium_pizza_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='small_pizza_weight',
            field=models.IntegerField(default=0),
        ),
    ]
