# Generated by Django 3.1.1 on 2020-10-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_auto_20201002_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
