# Generated by Django 3.1.1 on 2020-10-02 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_auto_20201002_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pizza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.category'),
        ),
    ]
