# Generated by Django 3.1.1 on 2020-10-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0017_auto_20201002_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ('category',)},
        ),
    ]
