# Generated by Django 3.1.1 on 2020-10-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0018_auto_20201002_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ('category', 'pizza_name')},
        ),
    ]
