# Generated by Django 3.1.1 on 2020-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0019_auto_20201002_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_img',
            field=models.ImageField(null=True, upload_to='pizza_images'),
        ),
    ]
