# Generated by Django 3.1.1 on 2020-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0024_auto_20201003_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
