# Generated by Django 3.1.1 on 2020-10-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0026_beverages_beveragescategory_beveragesprice_beveragesweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverages',
            options={'verbose_name_plural': 'Beverages'},
        ),
        migrations.AlterModelOptions(
            name='beveragescategory',
            options={'verbose_name_plural': 'Beverages Categories'},
        ),
        migrations.AlterField(
            model_name='beverages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.beveragescategory'),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='drink_name',
            field=models.CharField(max_length=50),
        ),
    ]
