# Generated by Django 3.1.1 on 2020-10-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0027_auto_20201004_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beveragesprice',
            name='big_beverages',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beveragesprice',
            name='little_beverages',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beveragesprice',
            name='medium_beverages',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='beveragesweight',
            name='big_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beveragesweight',
            name='little_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beveragesweight',
            name='medium_weight',
            field=models.IntegerField(null=True),
        ),
    ]
