# Generated by Django 3.1.1 on 2020-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0029_auto_20201004_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beveragesprice',
            name='big_beverages',
        ),
        migrations.RemoveField(
            model_name='beveragesprice',
            name='little_beverages',
        ),
        migrations.RemoveField(
            model_name='beveragesprice',
            name='medium_beverages',
        ),
        migrations.RemoveField(
            model_name='beveragesweight',
            name='big_weight',
        ),
        migrations.RemoveField(
            model_name='beveragesweight',
            name='little_weight',
        ),
        migrations.RemoveField(
            model_name='beveragesweight',
            name='medium_weight',
        ),
        migrations.AddField(
            model_name='beveragesprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beveragesweight',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='beveragesprice',
            name='beverages',
        ),
        migrations.AddField(
            model_name='beveragesprice',
            name='beverages',
            field=models.ManyToManyField(to='pizza.Beverages'),
        ),
        migrations.RemoveField(
            model_name='beveragesweight',
            name='beverages',
        ),
        migrations.AddField(
            model_name='beveragesweight',
            name='beverages',
            field=models.ManyToManyField(to='pizza.Beverages'),
        ),
    ]
