# Generated by Django 3.1.1 on 2020-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0030_auto_20201004_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beveragesprice',
            name='beverages',
        ),
        migrations.RemoveField(
            model_name='beveragesweight',
            name='beverages',
        ),
        migrations.AddField(
            model_name='beverages',
            name='price',
            field=models.ManyToManyField(to='pizza.BeveragesPrice'),
        ),
        migrations.AddField(
            model_name='beverages',
            name='weight',
            field=models.ManyToManyField(to='pizza.BeveragesWeight'),
        ),
    ]
