# Generated by Django 3.1.1 on 2020-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0031_auto_20201004_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beveragesprice',
            name='price',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='beveragesweight',
            name='weight',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
