# Generated by Django 3.1.1 on 2020-10-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0032_auto_20201004_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beveragesprice',
            options={'ordering': ('price',)},
        ),
    ]
