# Generated by Django 3.1.1 on 2020-10-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0033_auto_20201005_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beveragesweight',
            options={'ordering': ('weight',)},
        ),
    ]
